
using System.ComponentModel;
using System;
using System.DirectoryServices;
using System.Drawing;
using System.Windows.Forms;

namespace MLSSRandomizerForm
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new Container();
            ComponentResourceManager manager = new ComponentResourceManager(typeof(Form1));
            this.SelectRomButton = new Button();
            this.textBox1 = new TextBox();
            this.label1 = new Label();
            this.button2 = new Button();
            this.directorySearcher1 = new DirectorySearcher();
            this.folderBrowserDialog1 = new FolderBrowserDialog();
            this.openFileDialog1 = new OpenFileDialog();
            this.SeedTextbox = new TextBox();
            this.label2 = new Label();
            this.saveFileDialog1 = new SaveFileDialog();
            this.checkBox1 = new CheckBox();
            this.Colors = new TabControl();
            this.tabPage1 = new TabPage();
            this.checkBox52 = new CheckBox();
            this.checkBox51 = new CheckBox();
            this.checkBox50 = new CheckBox();
            this.checkBox46 = new CheckBox();
            this.checkBox45 = new CheckBox();
            this.checkBox44 = new CheckBox();
            this.label3 = new Label();
            this.radioButton3 = new RadioButton();
            this.radioButton2 = new RadioButton();
            this.radioButton1 = new RadioButton();
            this.tabPage2 = new TabPage();
            this.checkBox33 = new CheckBox();
            this.checkBox34 = new CheckBox();
            this.checkBox4 = new CheckBox();
            this.checkBox2 = new CheckBox();
            this.checkBox3 = new CheckBox();
            this.checkBox22 = new CheckBox();
            this.checkBox5 = new CheckBox();
            this.checkBox6 = new CheckBox();
            this.checkBox8 = new CheckBox();
            this.checkBox7 = new CheckBox();
            this.checkBox18 = new CheckBox();
            this.checkBox9 = new CheckBox();
            this.checkBox19 = new CheckBox();
            this.checkBox10 = new CheckBox();
            this.tabPage3 = new TabPage();
            this.checkBox11 = new CheckBox();
            this.checkBox15 = new CheckBox();
            this.checkBox12 = new CheckBox();
            this.checkBox16 = new CheckBox();
            this.tabPage4 = new TabPage();
            this.checkBox47 = new CheckBox();
            this.checkBox21 = new CheckBox();
            this.checkBox13 = new CheckBox();
            this.checkBox17 = new CheckBox();
            this.checkBox14 = new CheckBox();
            this.tabPage6 = new TabPage();
            this.checkBox28 = new CheckBox();
            this.checkBox27 = new CheckBox();
            this.checkBox26 = new CheckBox();
            this.tabPage5 = new TabPage();
            this.checkBox43 = new CheckBox();
            this.checkBox42 = new CheckBox();
            this.checkBox41 = new CheckBox();
            this.checkBox39 = new CheckBox();
            this.checkBox38 = new CheckBox();
            this.checkBox37 = new CheckBox();
            this.checkBox36 = new CheckBox();
            this.checkBox32 = new CheckBox();
            this.checkBox30 = new CheckBox();
            this.checkBox29 = new CheckBox();
            this.checkBox24 = new CheckBox();
            this.checkBox23 = new CheckBox();
            this.checkBox20 = new CheckBox();
            this.tabPage7 = new TabPage();
            this.button5 = new Button();
            this.button4 = new Button();
            this.button3 = new Button();
            this.button1 = new Button();
            this.numericUpDown4 = new NumericUpDown();
            this.numericUpDown1 = new NumericUpDown();
            this.numericUpDown3 = new NumericUpDown();
            this.label13 = new Label();
            this.label12 = new Label();
            this.label11 = new Label();
            this.label10 = new Label();
            this.label9 = new Label();
            this.panel1 = new Panel();
            this.label8 = new Label();
            this.comboBox4 = new ComboBox();
            this.label4 = new Label();
            this.label5 = new Label();
            this.comboBox3 = new ComboBox();
            this.comboBox1 = new ComboBox();
            this.comboBox2 = new ComboBox();
            this.label7 = new Label();
            this.tabPage9 = new TabPage();
            this.checkBox48 = new CheckBox();
            this.checkBox40 = new CheckBox();
            this.label14 = new Label();
            this.radioButton6 = new RadioButton();
            this.radioButton7 = new RadioButton();
            this.radioButton8 = new RadioButton();
            this.checkBox25 = new CheckBox();
            this.checkBox31 = new CheckBox();
            this.label6 = new Label();
            this.radioButton5 = new RadioButton();
            this.radioButton4 = new RadioButton();
            this.statCountBindingSource = new BindingSource(this.components);
            this.tabControl2 = new TabControl();
            this.tabPage8 = new TabPage();
            this.checkBox35 = new CheckBox();
            this.saveFileDialog2 = new SaveFileDialog();
            this.button6 = new Button();
            this.button7 = new Button();
            this.openFileDialog2 = new OpenFileDialog();
            this.saveFileDialog3 = new SaveFileDialog();
            this.toolTip1 = new ToolTip(this.components);
            this.checkBox49 = new CheckBox();
            this.form1BindingSource = new BindingSource(this.components);
            this.form1BindingSource1 = new BindingSource(this.components);
            this.romBindingSource = new BindingSource(this.components);
            this.Colors.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.tabPage6.SuspendLayout();
            this.tabPage5.SuspendLayout();
            this.tabPage7.SuspendLayout();
            this.numericUpDown4.BeginInit();
            this.numericUpDown1.BeginInit();
            this.numericUpDown3.BeginInit();
            this.tabPage9.SuspendLayout();
            ((ISupportInitialize)this.statCountBindingSource).BeginInit();
            this.tabControl2.SuspendLayout();
            this.tabPage8.SuspendLayout();
            ((ISupportInitialize)this.form1BindingSource).BeginInit();
            ((ISupportInitialize)this.form1BindingSource1).BeginInit();
            ((ISupportInitialize)this.romBindingSource).BeginInit();
            base.SuspendLayout();
            this.SelectRomButton.Location = new Point(0x181, 6);
            this.SelectRomButton.Name = "SelectRomButton";
            this.SelectRomButton.Size = new Size(0x1a, 0x17);
            this.SelectRomButton.TabIndex = 1;
            this.SelectRomButton.Text = "...";
            this.toolTip1.SetToolTip(this.SelectRomButton, "Select a Valid US ROM.");
            this.SelectRomButton.UseVisualStyleBackColor = true;
            this.SelectRomButton.Click += new EventHandler(this.SelectRomButton_Click);
            this.textBox1.Location = new Point(0xc4, 8);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(0xb7, 20);
            this.textBox1.TabIndex = 2;
            this.textBox1.TextChanged += new EventHandler(this.textBox1_TextChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(0x80, 11);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x41, 13);
            this.label1.TabIndex = 3;
            this.label1.Text = "Select Rom:";
            this.label1.Click += new EventHandler(this.label1_Click);
            this.button2.Location = new Point(0x150, 0x11c);
            this.button2.Name = "button2";
            this.button2.Size = new Size(0x4b, 0x17);
            this.button2.TabIndex = 4;
            this.button2.Text = "Randomize";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new EventHandler(this.button2_Click);
            this.directorySearcher1.ClientTimeout = TimeSpan.Parse("-00:00:01");
            this.directorySearcher1.ServerPageTimeLimit = TimeSpan.Parse("-00:00:01");
            this.directorySearcher1.ServerTimeLimit = TimeSpan.Parse("-00:00:01");
            this.openFileDialog1.FileName = "openFileDialog1";
            this.SeedTextbox.Location = new Point(0x108, 0x105);
            this.SeedTextbox.Name = "SeedTextbox";
            this.SeedTextbox.Size = new Size(0x93, 20);
            this.SeedTextbox.TabIndex = 5;
            this.SeedTextbox.TextChanged += new EventHandler(this.SeedTextbox_TextChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(0xdf, 0x108);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x23, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "Seed:";
            this.label2.Click += new EventHandler(this.label2_Click);
            this.saveFileDialog1.DefaultExt = "gba";
            this.saveFileDialog1.Filter = "Gameboy Advance Rom (*.gba)|*.gba|All files (*.*)|*.*";
            this.checkBox1.AutoSize = true;
            this.checkBox1.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox1.Location = new Point(100, 100);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new Size(0x4d, 0x11);
            this.checkBox1.TabIndex = 8;
            this.checkBox1.Text = "Skip Intro?";
            this.toolTip1.SetToolTip(this.checkBox1, "Checking this will skip the entire intro sequence of the game.\r\nYou will spawn in from Pipe 1, get High and Spin Jump immediately, and put the game in a state right after Tolstar is defeated.");
            this.checkBox1.UseVisualStyleBackColor = true;
            this.checkBox1.CheckedChanged += new EventHandler(this.checkBox1_CheckedChanged);
            this.Colors.Controls.Add(this.tabPage1);
            this.Colors.Controls.Add(this.tabPage2);
            this.Colors.Controls.Add(this.tabPage3);
            this.Colors.Controls.Add(this.tabPage4);
            this.Colors.Controls.Add(this.tabPage6);
            this.Colors.Controls.Add(this.tabPage5);
            this.Colors.Controls.Add(this.tabPage7);
            this.Colors.Controls.Add(this.tabPage9);
            this.Colors.Location = new Point(0x19, 0x20);
            this.Colors.Name = "Colors";
            this.Colors.SelectedIndex = 0;
            this.Colors.Size = new Size(0x182, 0xda);
            this.Colors.TabIndex = 9;
            this.Colors.Visible = false;
            this.tabPage1.Controls.Add(this.checkBox52);
            this.tabPage1.Controls.Add(this.checkBox51);
            this.tabPage1.Controls.Add(this.checkBox50);
            this.tabPage1.Controls.Add(this.checkBox46);
            this.tabPage1.Controls.Add(this.checkBox45);
            this.tabPage1.Controls.Add(this.checkBox44);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Controls.Add(this.radioButton3);
            this.tabPage1.Controls.Add(this.radioButton2);
            this.tabPage1.Controls.Add(this.radioButton1);
            this.tabPage1.ImeMode = ImeMode.On;
            this.tabPage1.Location = new Point(4, 0x16);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(0x17a, 0xc0);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Items";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tabPage1.Click += new EventHandler(this.tabPage1_Click);
            this.checkBox52.AutoSize = true;
            this.checkBox52.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox52.Location = new Point(0x9c, 0x58);
            this.checkBox52.Name = "checkBox52";
            this.checkBox52.Size = new Size(0xb7, 0x11);
            this.checkBox52.TabIndex = 0x1d;
            this.checkBox52.Text = "Add Harhall's Pants to Item Pool?";
            this.toolTip1.SetToolTip(this.checkBox52, "Checking this will add harhall's pants to the item pool.");
            this.checkBox52.UseVisualStyleBackColor = true;
            this.checkBox52.CheckedChanged += new EventHandler(this.checkBox52_CheckedChanged);
            this.checkBox51.AutoSize = true;
            this.checkBox51.Location = new Point(0x17, 0x81);
            this.checkBox51.Name = "checkBox51";
            this.checkBox51.Size = new Size(0x55, 0x11);
            this.checkBox51.TabIndex = 0x1c;
            this.checkBox51.Text = "Coin Boxes?";
            this.toolTip1.SetToolTip(this.checkBox51, "Checking this will add all coin boxes to the item pool.");
            this.checkBox51.UseVisualStyleBackColor = true;
            this.checkBox51.CheckedChanged += new EventHandler(this.checkBox51_CheckedChanged);
            this.checkBox50.AutoSize = true;
            this.checkBox50.Checked = true;
            this.checkBox50.CheckState = CheckState.Checked;
            this.checkBox50.Location = new Point(0x17, 0x6a);
            this.checkBox50.Name = "checkBox50";
            this.checkBox50.Size = new Size(0x88, 0x11);
            this.checkBox50.TabIndex = 0x1b;
            this.checkBox50.Text = "Item Boxes and Moles?";
            this.toolTip1.SetToolTip(this.checkBox50, "Checking this will add all item boxes and Monty Mole rewards to the item pool.");
            this.checkBox50.UseVisualStyleBackColor = true;
            this.checkBox50.CheckedChanged += new EventHandler(this.checkBox50_CheckedChanged);
            this.checkBox46.AutoSize = true;
            this.checkBox46.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox46.Location = new Point(0x7d, 0x41);
            this.checkBox46.Name = "checkBox46";
            this.checkBox46.Size = new Size(0xd6, 0x11);
            this.checkBox46.TabIndex = 0x1a;
            this.checkBox46.Text = "Remove Hidden Blocks from Item Pool?";
            this.toolTip1.SetToolTip(this.checkBox46, "Checking this will remove any hidden blocks from the item pool.");
            this.checkBox46.UseVisualStyleBackColor = true;
            this.checkBox46.CheckedChanged += new EventHandler(this.checkBox46_CheckedChanged);
            this.checkBox45.AutoSize = true;
            this.checkBox45.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox45.Location = new Point(0x7a, 0x2a);
            this.checkBox45.Name = "checkBox45";
            this.checkBox45.Size = new Size(0xd9, 0x11);
            this.checkBox45.TabIndex = 0x19;
            this.checkBox45.Text = "Turn all Item Blocks into Hidden Blocks?";
            this.toolTip1.SetToolTip(this.checkBox45, "Checking this will turn all Item blocks into Hidden blocks.");
            this.checkBox45.UseVisualStyleBackColor = true;
            this.checkBox45.CheckedChanged += new EventHandler(this.checkBox45_CheckedChanged);
            this.checkBox44.AutoSize = true;
            this.checkBox44.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox44.Location = new Point(0xa7, 0x12);
            this.checkBox44.Name = "checkBox44";
            this.checkBox44.Size = new Size(0xac, 0x11);
            this.checkBox44.TabIndex = 0x18;
            this.checkBox44.Text = "Turn all Hidden Blocks Visible?";
            this.toolTip1.SetToolTip(this.checkBox44, "Checking this will turn all hidden blocks into regular ones.");
            this.checkBox44.UseVisualStyleBackColor = true;
            this.checkBox44.CheckedChanged += new EventHandler(this.checkBox44_CheckedChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(20, 0x13);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x55, 13);
            this.label3.TabIndex = 3;
            this.label3.Text = "Chuckle Beans?";
            this.label3.Click += new EventHandler(this.label3_Click_2);
            this.radioButton3.AutoSize = true;
            this.radioButton3.Checked = true;
            this.radioButton3.Location = new Point(0x17, 0x53);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.Size = new Size(0x24, 0x11);
            this.radioButton3.TabIndex = 2;
            this.radioButton3.TabStop = true;
            this.radioButton3.Text = "All";
            this.toolTip1.SetToolTip(this.radioButton3, "All chuckle beans will be added to the item pool.");
            this.radioButton3.UseVisualStyleBackColor = true;
            this.radioButton3.CheckedChanged += new EventHandler(this.radioButton3_CheckedChanged);
            this.radioButton3.MouseHover += new EventHandler(this.radioButton3_MouseHover);
            this.radioButton2.AutoSize = true;
            this.radioButton2.Location = new Point(0x17, 60);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new Size(0x4f, 0x11);
            this.radioButton2.TabIndex = 1;
            this.radioButton2.Text = "Only Visible";
            this.toolTip1.SetToolTip(this.radioButton2, "Only chuckle beans clearly marked with an X will be added to the item pool.");
            this.radioButton2.UseVisualStyleBackColor = true;
            this.radioButton2.CheckedChanged += new EventHandler(this.radioButton2_CheckedChanged);
            this.radioButton2.MouseHover += new EventHandler(this.radioButton2_MouseHover);
            this.radioButton1.AutoSize = true;
            this.radioButton1.Location = new Point(0x17, 0x25);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new Size(0x33, 0x11);
            this.radioButton1.TabIndex = 0;
            this.radioButton1.Text = "None";
            this.toolTip1.SetToolTip(this.radioButton1, "No Chuckle Beans will be added to the item pool.");
            this.radioButton1.UseVisualStyleBackColor = true;
            this.radioButton1.CheckedChanged += new EventHandler(this.radioButton1_CheckedChanged);
            this.radioButton1.MouseHover += new EventHandler(this.radioButton1_MouseHover);
            this.tabPage2.Controls.Add(this.checkBox33);
            this.tabPage2.Controls.Add(this.checkBox34);
            this.tabPage2.Controls.Add(this.checkBox4);
            this.tabPage2.Controls.Add(this.checkBox2);
            this.tabPage2.Controls.Add(this.checkBox3);
            this.tabPage2.Controls.Add(this.checkBox22);
            this.tabPage2.Controls.Add(this.checkBox5);
            this.tabPage2.Controls.Add(this.checkBox6);
            this.tabPage2.Controls.Add(this.checkBox8);
            this.tabPage2.Controls.Add(this.checkBox7);
            this.tabPage2.Controls.Add(this.checkBox18);
            this.tabPage2.Controls.Add(this.checkBox9);
            this.tabPage2.Controls.Add(this.checkBox19);
            this.tabPage2.Controls.Add(this.checkBox10);
            this.tabPage2.Location = new Point(4, 0x16);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x17a, 0xc0);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Key Items";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.checkBox33.AutoSize = true;
            this.checkBox33.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox33.Checked = true;
            this.checkBox33.CheckState = CheckState.Checked;
            this.checkBox33.Location = new Point(0xc0, 0x9d);
            this.checkBox33.Name = "checkBox33";
            this.checkBox33.Size = new Size(0x6d, 0x11);
            this.checkBox33.TabIndex = 0x17;
            this.checkBox33.Text = "Beanstar Pieces?";
            this.toolTip1.SetToolTip(this.checkBox33, "Checking this will add the Beanstar Pieces to the item pool.\r\nYou must gather all 4 pieces and reassemble the beanstar as an extra requirement to beat the game.");
            this.checkBox33.UseVisualStyleBackColor = true;
            this.checkBox33.CheckedChanged += new EventHandler(this.checkBox33_CheckedChanged);
            this.checkBox34.AutoSize = true;
            this.checkBox34.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox34.Checked = true;
            this.checkBox34.CheckState = CheckState.Checked;
            this.checkBox34.Location = new Point(80, 0x9d);
            this.checkBox34.Name = "checkBox34";
            this.checkBox34.Size = new Size(0x47, 0x11);
            this.checkBox34.TabIndex = 0x16;
            this.checkBox34.Text = "Spangle?";
            this.toolTip1.SetToolTip(this.checkBox34, "Checking this will add Spangle to the item pool.\r\nGive Spangle to Hermie in Gwahar lagoon for a reward.");
            this.checkBox34.UseVisualStyleBackColor = true;
            this.checkBox34.CheckedChanged += new EventHandler(this.checkBox34_CheckedChanged);
            this.checkBox4.AutoSize = true;
            this.checkBox4.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox4.Checked = true;
            this.checkBox4.CheckState = CheckState.Checked;
            this.checkBox4.Location = new Point(0x33, 0x2a);
            this.checkBox4.Name = "checkBox4";
            this.checkBox4.Size = new Size(100, 0x11);
            this.checkBox4.TabIndex = 12;
            this.checkBox4.Text = "Chuckola Fruit?";
            this.toolTip1.SetToolTip(this.checkBox4, "Checking this will add all 3 Chuckola Fruits to the item pool.\r\nUse all 3 fruits to progress past Chuckleroot in Chucklehuck woods");
            this.checkBox4.UseVisualStyleBackColor = true;
            this.checkBox4.CheckedChanged += new EventHandler(this.checkBox4_CheckedChanged);
            this.checkBox2.AutoSize = true;
            this.checkBox2.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox2.Checked = true;
            this.checkBox2.CheckState = CheckState.Checked;
            this.checkBox2.Location = new Point(0x2f, 0x13);
            this.checkBox2.Name = "checkBox2";
            this.checkBox2.Size = new Size(0x68, 0x11);
            this.checkBox2.TabIndex = 10;
            this.checkBox2.Text = "Peasley's Rose?";
            this.toolTip1.SetToolTip(this.checkBox2, "Checking this will add Peasley's Rose to the item pool.\r\nYou can use Peasley's Rose to enter Beanbean Castle.");
            this.checkBox2.UseVisualStyleBackColor = true;
            this.checkBox2.CheckedChanged += new EventHandler(this.checkBox2_CheckedChanged);
            this.checkBox3.AutoSize = true;
            this.checkBox3.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox3.Checked = true;
            this.checkBox3.CheckState = CheckState.Checked;
            this.checkBox3.Location = new Point(0xb7, 0x13);
            this.checkBox3.Name = "checkBox3";
            this.checkBox3.Size = new Size(0x76, 0x11);
            this.checkBox3.TabIndex = 11;
            this.checkBox3.Text = "Beanbean Brooch?";
            this.toolTip1.SetToolTip(this.checkBox3, "Checking this will add the beanbean Brooch to the item pool.\r\nThe Beanbean Brooch will let you enter ChuckleHuck Woods.");
            this.checkBox3.UseVisualStyleBackColor = true;
            this.checkBox3.CheckedChanged += new EventHandler(this.checkBox3_CheckedChanged);
            this.checkBox22.AutoSize = true;
            this.checkBox22.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox22.Checked = true;
            this.checkBox22.CheckState = CheckState.Checked;
            this.checkBox22.Location = new Point(0xe4, 0x86);
            this.checkBox22.Name = "checkBox22";
            this.checkBox22.Size = new Size(0x49, 0x11);
            this.checkBox22.TabIndex = 0x15;
            this.checkBox22.Text = "Beanlets?";
            this.toolTip1.SetToolTip(this.checkBox22, "Checking this will add all 5 Beanlets to the item pool. These serve no purpose.");
            this.checkBox22.UseVisualStyleBackColor = true;
            this.checkBox22.CheckedChanged += new EventHandler(this.checkBox22_CheckedChanged);
            this.checkBox5.AutoSize = true;
            this.checkBox5.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox5.Checked = true;
            this.checkBox5.CheckState = CheckState.Checked;
            this.checkBox5.Location = new Point(0xbb, 0x2a);
            this.checkBox5.Name = "checkBox5";
            this.checkBox5.Size = new Size(0x72, 0x11);
            this.checkBox5.TabIndex = 13;
            this.checkBox5.Text = "Membership Card?";
            this.toolTip1.SetToolTip(this.checkBox5, "Checking this will add the Membership card to the item pool.\r\nUse this to sink the S.S Chuckola.");
            this.checkBox5.UseVisualStyleBackColor = true;
            this.checkBox5.CheckedChanged += new EventHandler(this.checkBox5_CheckedChanged);
            this.checkBox6.AutoSize = true;
            this.checkBox6.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox6.Checked = true;
            this.checkBox6.CheckState = CheckState.Checked;
            this.checkBox6.Location = new Point(0x3d, 0x41);
            this.checkBox6.Name = "checkBox6";
            this.checkBox6.Size = new Size(90, 0x11);
            this.checkBox6.TabIndex = 14;
            this.checkBox6.Text = "Winkle Card?";
            this.toolTip1.SetToolTip(this.checkBox6, "Checking this will add the Winkle Card to the pool.\r\nUse this to enter the Winkle area in ChuckleHuck woods.");
            this.checkBox6.UseVisualStyleBackColor = true;
            this.checkBox6.CheckedChanged += new EventHandler(this.checkBox6_CheckedChanged);
            this.checkBox8.AutoSize = true;
            this.checkBox8.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox8.Checked = true;
            this.checkBox8.CheckState = CheckState.Checked;
            this.checkBox8.Location = new Point(0xd7, 0x41);
            this.checkBox8.Name = "checkBox8";
            this.checkBox8.Size = new Size(0x56, 0x11);
            this.checkBox8.TabIndex = 0x10;
            this.checkBox8.Text = "Extra Dress?";
            this.toolTip1.SetToolTip(this.checkBox8, "Checking this will add Peach's Extra Dress to the itme pool.\r\nYou will need the dress to progress past Joke's End.");
            this.checkBox8.UseVisualStyleBackColor = true;
            this.checkBox8.CheckedChanged += new EventHandler(this.checkBox8_CheckedChanged);
            this.checkBox7.AutoSize = true;
            this.checkBox7.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox7.Checked = true;
            this.checkBox7.CheckState = CheckState.Checked;
            this.checkBox7.Location = new Point(50, 0x58);
            this.checkBox7.Name = "checkBox7";
            this.checkBox7.Size = new Size(0x65, 0x11);
            this.checkBox7.TabIndex = 15;
            this.checkBox7.Text = "Fake Beanstar?";
            this.toolTip1.SetToolTip(this.checkBox7, "Checking this will add the Fake Beanstar to the itme pool.\r\nYou will need the fake beanstar to progress past Joke's End.");
            this.checkBox7.UseVisualStyleBackColor = true;
            this.checkBox7.CheckedChanged += new EventHandler(this.checkBox7_CheckedChanged);
            this.checkBox18.AutoSize = true;
            this.checkBox18.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox18.Checked = true;
            this.checkBox18.CheckState = CheckState.Checked;
            this.checkBox18.Location = new Point(0xcc, 0x6f);
            this.checkBox18.Name = "checkBox18";
            this.checkBox18.Size = new Size(0x61, 0x11);
            this.checkBox18.TabIndex = 0x13;
            this.checkBox18.Text = "Secret Scrolls?";
            this.toolTip1.SetToolTip(this.checkBox18, "Checking this will add the secret scrolls to the item pool.\r\nUse these to unlock new Bros. Attacks in combat.");
            this.checkBox18.UseVisualStyleBackColor = true;
            this.checkBox18.CheckedChanged += new EventHandler(this.checkBox18_CheckedChanged);
            this.checkBox9.AutoSize = true;
            this.checkBox9.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox9.Checked = true;
            this.checkBox9.CheckState = CheckState.Checked;
            this.checkBox9.Location = new Point(0xe3, 0x58);
            this.checkBox9.Name = "checkBox9";
            this.checkBox9.Size = new Size(0x4a, 0x11);
            this.checkBox9.TabIndex = 0x11;
            this.checkBox9.Text = "Beanfruit?";
            this.toolTip1.SetToolTip(this.checkBox9, "Checking this will add all 7 Beanfruit to the item pool.\r\nUse these to feed the yoshi in Yoshi's Theater for rewards.");
            this.checkBox9.UseVisualStyleBackColor = true;
            this.checkBox9.CheckedChanged += new EventHandler(this.checkBox9_CheckedChanged);
            this.checkBox19.AutoSize = true;
            this.checkBox19.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox19.Checked = true;
            this.checkBox19.CheckState = CheckState.Checked;
            this.checkBox19.Location = new Point(0x3f, 0x86);
            this.checkBox19.Name = "checkBox19";
            this.checkBox19.Size = new Size(0x58, 0x11);
            this.checkBox19.TabIndex = 20;
            this.checkBox19.Text = "Beanstones?";
            this.toolTip1.SetToolTip(this.checkBox19, "Checking this will add all 10 Beanstones to the item pool. These do not serve a purpose.");
            this.checkBox19.UseVisualStyleBackColor = true;
            this.checkBox19.CheckedChanged += new EventHandler(this.checkBox19_CheckedChanged);
            this.checkBox10.AutoSize = true;
            this.checkBox10.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox10.Checked = true;
            this.checkBox10.CheckState = CheckState.Checked;
            this.checkBox10.Location = new Point(0x42, 0x6f);
            this.checkBox10.Name = "checkBox10";
            this.checkBox10.Size = new Size(0x55, 0x11);
            this.checkBox10.TabIndex = 0x12;
            this.checkBox10.Text = "Neon Eggs?";
            this.toolTip1.SetToolTip(this.checkBox10, "Checking this will add all 7 Neon Eggs to the Item Pool.\r\nCollect all 7 to the the beanstar piece in Yoshi's Theater");
            this.checkBox10.UseVisualStyleBackColor = true;
            this.checkBox10.CheckedChanged += new EventHandler(this.checkBox10_CheckedChanged);
            this.tabPage3.Controls.Add(this.checkBox11);
            this.tabPage3.Controls.Add(this.checkBox15);
            this.tabPage3.Controls.Add(this.checkBox12);
            this.tabPage3.Controls.Add(this.checkBox16);
            this.tabPage3.Location = new Point(4, 0x16);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new Padding(3);
            this.tabPage3.Size = new Size(0x17a, 0xc0);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Bros Items";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.checkBox11.AutoSize = true;
            this.checkBox11.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox11.Checked = true;
            this.checkBox11.CheckState = CheckState.Checked;
            this.checkBox11.Location = new Point(0x4b, 0x12);
            this.checkBox11.Name = "checkBox11";
            this.checkBox11.Size = new Size(0x4c, 0x11);
            this.checkBox11.TabIndex = 0x12;
            this.checkBox11.Text = "Hammers?";
            this.toolTip1.SetToolTip(this.checkBox11, "Checking this will add all 3 Hammers to the item pool.");
            this.checkBox11.UseVisualStyleBackColor = true;
            this.checkBox11.CheckedChanged += new EventHandler(this.checkBox11_CheckedChanged);
            this.checkBox15.AutoSize = true;
            this.checkBox15.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox15.Checked = true;
            this.checkBox15.CheckState = CheckState.Checked;
            this.checkBox15.Location = new Point(0xb6, 0x12);
            this.checkBox15.Name = "checkBox15";
            this.checkBox15.Size = new Size(0x69, 0x11);
            this.checkBox15.TabIndex = 0x16;
            this.checkBox15.Text = "Hammer moves?";
            this.toolTip1.SetToolTip(this.checkBox15, "Checking this will add the Red and Green Goblet to the item pool.\r\nThese will give you the ability to dig and make mario small.");
            this.checkBox15.UseVisualStyleBackColor = true;
            this.checkBox15.CheckedChanged += new EventHandler(this.checkBox15_CheckedChanged);
            this.checkBox12.AutoSize = true;
            this.checkBox12.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox12.Checked = true;
            this.checkBox12.CheckState = CheckState.Checked;
            this.checkBox12.Location = new Point(0x58, 0x34);
            this.checkBox12.Name = "checkBox12";
            this.checkBox12.Size = new Size(0x3f, 0x11);
            this.checkBox12.TabIndex = 0x13;
            this.checkBox12.Text = "Hands?";
            this.toolTip1.SetToolTip(this.checkBox12, "Checking this will add Fire and Thunder Hand to the item pool.");
            this.checkBox12.UseVisualStyleBackColor = true;
            this.checkBox12.CheckedChanged += new EventHandler(this.checkBox12_CheckedChanged);
            this.checkBox16.AutoSize = true;
            this.checkBox16.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox16.Checked = true;
            this.checkBox16.CheckState = CheckState.Checked;
            this.checkBox16.Location = new Point(0xc2, 0x34);
            this.checkBox16.Name = "checkBox16";
            this.checkBox16.Size = new Size(0x5d, 0x11);
            this.checkBox16.TabIndex = 0x17;
            this.checkBox16.Text = "Hand Moves?";
            this.toolTip1.SetToolTip(this.checkBox16, "Checking this will and the Red and Green Pearl Beans to the item pool.\r\nGetting these will give you the fire Dash and Thunder Crash abilities.");
            this.checkBox16.UseVisualStyleBackColor = true;
            this.checkBox16.CheckedChanged += new EventHandler(this.checkBox16_CheckedChanged);
            this.tabPage4.Controls.Add(this.checkBox47);
            this.tabPage4.Controls.Add(this.checkBox21);
            this.tabPage4.Controls.Add(this.checkBox13);
            this.tabPage4.Controls.Add(this.checkBox17);
            this.tabPage4.Controls.Add(this.checkBox14);
            this.tabPage4.Location = new Point(4, 0x16);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new Padding(3);
            this.tabPage4.Size = new Size(0x17a, 0xc0);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "Shops";
            this.tabPage4.UseVisualStyleBackColor = true;
            this.checkBox47.AutoSize = true;
            this.checkBox47.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox47.Location = new Point(0xba, 0x2a);
            this.checkBox47.Name = "checkBox47";
            this.checkBox47.Size = new Size(0xa3, 0x11);
            this.checkBox47.TabIndex = 0x1b;
            this.checkBox47.Text = "No key items in coffee shop?";
            this.toolTip1.SetToolTip(this.checkBox47, "Checking this will make it so no Key Items can be placed in the Esprsoo shop when generating a seed.");
            this.checkBox47.UseVisualStyleBackColor = true;
            this.checkBox47.CheckedChanged += new EventHandler(this.checkBox47_CheckedChanged);
            this.checkBox21.AutoSize = true;
            this.checkBox21.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox21.Checked = true;
            this.checkBox21.CheckState = CheckState.Checked;
            this.checkBox21.Location = new Point(0x42, 0x12);
            this.checkBox21.Name = "checkBox21";
            this.checkBox21.Size = new Size(0x55, 0x11);
            this.checkBox21.TabIndex = 0x19;
            this.checkBox21.Text = "Item Shops?";
            this.toolTip1.SetToolTip(this.checkBox21, "Checking this will add all Items in the Item shop into the item pool.");
            this.checkBox21.UseVisualStyleBackColor = true;
            this.checkBox21.CheckedChanged += new EventHandler(this.checkBox21_CheckedChanged);
            this.checkBox13.AutoSize = true;
            this.checkBox13.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox13.Checked = true;
            this.checkBox13.CheckState = CheckState.Checked;
            this.checkBox13.Location = new Point(0x53, 0x54);
            this.checkBox13.Name = "checkBox13";
            this.checkBox13.Size = new Size(0x44, 0x11);
            this.checkBox13.TabIndex = 20;
            this.checkBox13.Text = "Badges?";
            this.toolTip1.SetToolTip(this.checkBox13, "Checking this will add all Items from the Badge Shop to the Item pool.");
            this.checkBox13.UseVisualStyleBackColor = true;
            this.checkBox13.CheckedChanged += new EventHandler(this.checkBox13_CheckedChanged);
            this.checkBox17.AutoSize = true;
            this.checkBox17.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox17.Checked = true;
            this.checkBox17.CheckState = CheckState.Checked;
            this.checkBox17.Location = new Point(0x113, 0x13);
            this.checkBox17.Name = "checkBox17";
            this.checkBox17.Size = new Size(0x4b, 0x11);
            this.checkBox17.TabIndex = 0x18;
            this.checkBox17.Text = "Espresso?";
            this.toolTip1.SetToolTip(this.checkBox17, "Checking this will add all 7 Espressos and all 7 E. Gadd rewards to the Item pool.");
            this.checkBox17.UseVisualStyleBackColor = true;
            this.checkBox17.CheckedChanged += new EventHandler(this.checkBox17_CheckedChanged);
            this.checkBox14.AutoSize = true;
            this.checkBox14.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox14.Checked = true;
            this.checkBox14.CheckState = CheckState.Checked;
            this.checkBox14.Location = new Point(0x5c, 0x34);
            this.checkBox14.Name = "checkBox14";
            this.checkBox14.Size = new Size(0x3b, 0x11);
            this.checkBox14.TabIndex = 0x15;
            this.checkBox14.Text = "Pants?";
            this.toolTip1.SetToolTip(this.checkBox14, "Checking this will add all Items form the Pants Shop to the Item pool.");
            this.checkBox14.UseVisualStyleBackColor = true;
            this.checkBox14.CheckedChanged += new EventHandler(this.checkBox14_CheckedChanged);
            this.tabPage6.Controls.Add(this.checkBox28);
            this.tabPage6.Controls.Add(this.checkBox27);
            this.tabPage6.Controls.Add(this.checkBox26);
            this.tabPage6.Location = new Point(4, 0x16);
            this.tabPage6.Name = "tabPage6";
            this.tabPage6.Padding = new Padding(3);
            this.tabPage6.Size = new Size(0x17a, 0xc0);
            this.tabPage6.TabIndex = 5;
            this.tabPage6.Text = "Stats";
            this.tabPage6.UseVisualStyleBackColor = true;
            this.checkBox28.AutoSize = true;
            this.checkBox28.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox28.Location = new Point(0x13, 0x41);
            this.checkBox28.Name = "checkBox28";
            this.checkBox28.Size = new Size(0x84, 0x11);
            this.checkBox28.TabIndex = 0x20;
            this.checkBox28.Text = "Espresso Stat Values?";
            this.toolTip1.SetToolTip(this.checkBox28, "Checking this will rnadomize the stat increase values of all 7 Espressos.");
            this.checkBox28.UseVisualStyleBackColor = true;
            this.checkBox28.CheckedChanged += new EventHandler(this.checkBox28_CheckedChanged);
            this.checkBox27.AutoSize = true;
            this.checkBox27.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox27.Location = new Point(0x27, 0x2a);
            this.checkBox27.Name = "checkBox27";
            this.checkBox27.Size = new Size(0x70, 0x11);
            this.checkBox27.TabIndex = 0x1f;
            this.checkBox27.Text = "Item Heal Values?";
            this.toolTip1.SetToolTip(this.checkBox27, "Checking this will randomize the Heal Values of all Mushrooms, Syrups, and Nuts.");
            this.checkBox27.UseVisualStyleBackColor = true;
            this.checkBox27.CheckedChanged += new EventHandler(this.checkBox27_CheckedChanged);
            this.checkBox26.AutoSize = true;
            this.checkBox26.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox26.Location = new Point(0x13, 0x13);
            this.checkBox26.Name = "checkBox26";
            this.checkBox26.Size = new Size(0x84, 0x11);
            this.checkBox26.TabIndex = 30;
            this.checkBox26.Text = "Bros. Move BP Costs?";
            this.toolTip1.SetToolTip(this.checkBox26, "Checking this will randomize the BP costs of all Bros. Moves.");
            this.checkBox26.UseVisualStyleBackColor = true;
            this.checkBox26.CheckedChanged += new EventHandler(this.checkBox26_CheckedChanged);
            this.tabPage5.Controls.Add(this.checkBox43);
            this.tabPage5.Controls.Add(this.checkBox42);
            this.tabPage5.Controls.Add(this.checkBox41);
            this.tabPage5.Controls.Add(this.checkBox39);
            this.tabPage5.Controls.Add(this.checkBox38);
            this.tabPage5.Controls.Add(this.checkBox37);
            this.tabPage5.Controls.Add(this.checkBox36);
            this.tabPage5.Controls.Add(this.checkBox32);
            this.tabPage5.Controls.Add(this.checkBox30);
            this.tabPage5.Controls.Add(this.checkBox29);
            this.tabPage5.Controls.Add(this.checkBox24);
            this.tabPage5.Controls.Add(this.checkBox23);
            this.tabPage5.Controls.Add(this.checkBox1);
            this.tabPage5.Controls.Add(this.checkBox20);
            this.tabPage5.Location = new Point(4, 0x16);
            this.tabPage5.Name = "tabPage5";
            this.tabPage5.Padding = new Padding(3);
            this.tabPage5.Size = new Size(0x17a, 0xc0);
            this.tabPage5.TabIndex = 4;
            this.tabPage5.Text = "Misc.";
            this.tabPage5.UseVisualStyleBackColor = true;
            this.checkBox43.AutoSize = true;
            this.checkBox43.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox43.Location = new Point(50, 0x7b);
            this.checkBox43.Name = "checkBox43";
            this.checkBox43.Size = new Size(0x7f, 0x11);
            this.checkBox43.TabIndex = 0x2e;
            this.checkBox43.Text = "Start in Castle Town?";
            this.toolTip1.SetToolTip(this.checkBox43, "Checking this will do the same thing as Skip intro, except you will spawn in Pipe 3 instead of Pipe 1.");
            this.checkBox43.UseVisualStyleBackColor = true;
            this.checkBox43.CheckedChanged += new EventHandler(this.checkBox43_CheckedChanged);
            this.checkBox42.AutoSize = true;
            this.checkBox42.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox42.Location = new Point(0x43, 0xa9);
            this.checkBox42.Name = "checkBox42";
            this.checkBox42.Size = new Size(110, 0x11);
            this.checkBox42.TabIndex = 0x2d;
            this.checkBox42.Text = "Randomize Luigi?";
            this.toolTip1.SetToolTip(this.checkBox42, "Checking this will add Luigi into the item pool as an Item.\r\nYou can play as solo mario until you find him.");
            this.checkBox42.UseVisualStyleBackColor = true;
            this.checkBox42.CheckedChanged += new EventHandler(this.checkBox42_CheckedChanged);
            this.checkBox41.AutoSize = true;
            this.checkBox41.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox41.Location = new Point(0x3f, 0x92);
            this.checkBox41.Name = "checkBox41";
            this.checkBox41.Size = new Size(0x72, 0x11);
            this.checkBox41.TabIndex = 0x2c;
            this.checkBox41.Text = "Randomize Mario?";
            this.toolTip1.SetToolTip(this.checkBox41, "Checking this will add Mario into the item pool as an Item.\r\nYou can play as solo luigi until you find him.");
            this.checkBox41.UseVisualStyleBackColor = true;
            this.checkBox41.CheckedChanged += new EventHandler(this.checkBox41_CheckedChanged);
            this.checkBox39.AutoSize = true;
            this.checkBox39.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox39.Enabled = false;
            this.checkBox39.Location = new Point(0xfb, 0x1f);
            this.checkBox39.Name = "checkBox39";
            this.checkBox39.Size = new Size(0x74, 0x11);
            this.checkBox39.TabIndex = 0x2b;
            this.checkBox39.Text = "Randomize Doors?";
            this.toolTip1.SetToolTip(this.checkBox39, "Checking this will randomize All Entrances in the game. Entering a door will take you to a random location in the game.");
            this.checkBox39.UseVisualStyleBackColor = true;
            this.checkBox39.Visible = false;
            this.checkBox39.CheckedChanged += new EventHandler(this.checkBox39_CheckedChanged);
            this.checkBox38.AutoSize = true;
            this.checkBox38.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox38.Location = new Point(0xf3, 100);
            this.checkBox38.Name = "checkBox38";
            this.checkBox38.Size = new Size(0x7c, 0x11);
            this.checkBox38.TabIndex = 0x2a;
            this.checkBox38.Text = "Randomize Sounds?";
            this.toolTip1.SetToolTip(this.checkBox38, "Checking this will randomize all sounds in the game.");
            this.checkBox38.UseVisualStyleBackColor = true;
            this.checkBox38.CheckedChanged += new EventHandler(this.checkBox38_CheckedChanged);
            this.checkBox37.AutoSize = true;
            this.checkBox37.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox37.Location = new Point(0x10d, 0x92);
            this.checkBox37.Name = "checkBox37";
            this.checkBox37.Size = new Size(0x62, 0x11);
            this.checkBox37.TabIndex = 0x29;
            this.checkBox37.Text = "Disable Music?";
            this.toolTip1.SetToolTip(this.checkBox37, "Checking this will mute all music in the game. You can still hear all other sounds.");
            this.checkBox37.UseVisualStyleBackColor = true;
            this.checkBox37.CheckedChanged += new EventHandler(this.checkBox37_CheckedChanged);
            this.checkBox36.AutoSize = true;
            this.checkBox36.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox36.Location = new Point(0xd6, 0x4d);
            this.checkBox36.Name = "checkBox36";
            this.checkBox36.Size = new Size(0x99, 0x11);
            this.checkBox36.TabIndex = 40;
            this.checkBox36.Text = "Enable Minigame Spoilers?";
            this.toolTip1.SetToolTip(this.checkBox36, "Checking this will give you ingame spoilers on certain items that are behind minigames. Stand in fronr of the specific NPC/Sign to see what item is behind the minigame.");
            this.checkBox36.UseVisualStyleBackColor = true;
            this.checkBox36.CheckedChanged += new EventHandler(this.checkBox36_CheckedChanged_1);
            this.checkBox32.AutoSize = true;
            this.checkBox32.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox32.Location = new Point(0x12, 0x36);
            this.checkBox32.Name = "checkBox32";
            this.checkBox32.Size = new Size(0x9f, 0x11);
            this.checkBox32.TabIndex = 0x27;
            this.checkBox32.Text = "Disable Minecart Minigame?";
            this.toolTip1.SetToolTip(this.checkBox32, "Checking this will remove the minecart minigame from the game, making passage from hoohoo mountain to beanbean outskirts much smoother.");
            this.checkBox32.UseVisualStyleBackColor = true;
            this.checkBox32.CheckedChanged += new EventHandler(this.checkBox32_CheckedChanged);
            this.checkBox30.AutoSize = true;
            this.checkBox30.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox30.Location = new Point(0xba, 0x36);
            this.checkBox30.Name = "checkBox30";
            this.checkBox30.Size = new Size(0xb5, 0x11);
            this.checkBox30.TabIndex = 0x1f;
            this.checkBox30.Text = "Randomize Battle Backgrounds?";
            this.toolTip1.SetToolTip(this.checkBox30, "Checking this will randomize the background image of all battles.");
            this.checkBox30.UseVisualStyleBackColor = true;
            this.checkBox30.CheckedChanged += new EventHandler(this.checkBox30_CheckedChanged_1);
            this.checkBox29.AutoSize = true;
            this.checkBox29.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox29.Location = new Point(0xfb, 0x7b);
            this.checkBox29.Name = "checkBox29";
            this.checkBox29.Size = new Size(0x74, 0x11);
            this.checkBox29.TabIndex = 30;
            this.checkBox29.Text = "Randomize Music?";
            this.toolTip1.SetToolTip(this.checkBox29, "Checking this will randomize all music in the game.");
            this.checkBox29.UseVisualStyleBackColor = true;
            this.checkBox29.CheckedChanged += new EventHandler(this.checkBox29_CheckedChanged);
            this.checkBox24.AutoSize = true;
            this.checkBox24.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox24.Location = new Point(0x2f, 0x4d);
            this.checkBox24.Name = "checkBox24";
            this.checkBox24.Size = new Size(130, 0x11);
            this.checkBox24.TabIndex = 0x1c;
            this.checkBox24.Text = "Skip Bowser's Castle?";
            this.toolTip1.SetToolTip(this.checkBox24, "Checking this will remove all items from bowser's castle from the item pool, and let you skip stright to the final boss once you enter the castle.\r\n");
            this.checkBox24.UseVisualStyleBackColor = true;
            this.checkBox24.CheckedChanged += new EventHandler(this.checkBox24_CheckedChanged);
            this.checkBox23.AutoSize = true;
            this.checkBox23.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox23.Location = new Point(40, 0x1f);
            this.checkBox23.Name = "checkBox23";
            this.checkBox23.Size = new Size(0x89, 0x11);
            this.checkBox23.TabIndex = 0x1b;
            this.checkBox23.Text = "Disable Surf Minigame?";
            this.toolTip1.SetToolTip(this.checkBox23, "Checking this will remove the reward from the surf minigame from the item pool.");
            this.checkBox23.UseVisualStyleBackColor = true;
            this.checkBox23.CheckedChanged += new EventHandler(this.checkBox23_CheckedChanged);
            this.checkBox20.AutoSize = true;
            this.checkBox20.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox20.Location = new Point(0x2f, 8);
            this.checkBox20.Name = "checkBox20";
            this.checkBox20.Size = new Size(130, 0x11);
            this.checkBox20.TabIndex = 0x1a;
            this.checkBox20.Text = "Disable Mush Badge?";
            this.toolTip1.SetToolTip(this.checkBox20, "Checking this will remove all 3 Mush Badges from the Game, including in the vanilla locations.");
            this.checkBox20.UseVisualStyleBackColor = true;
            this.checkBox20.CheckedChanged += new EventHandler(this.checkBox20_CheckedChanged);
            this.tabPage7.Controls.Add(this.button5);
            this.tabPage7.Controls.Add(this.button4);
            this.tabPage7.Controls.Add(this.button3);
            this.tabPage7.Controls.Add(this.button1);
            this.tabPage7.Controls.Add(this.numericUpDown4);
            this.tabPage7.Controls.Add(this.numericUpDown1);
            this.tabPage7.Controls.Add(this.numericUpDown3);
            this.tabPage7.Controls.Add(this.label13);
            this.tabPage7.Controls.Add(this.label12);
            this.tabPage7.Controls.Add(this.label11);
            this.tabPage7.Controls.Add(this.label10);
            this.tabPage7.Controls.Add(this.label9);
            this.tabPage7.Controls.Add(this.panel1);
            this.tabPage7.Controls.Add(this.label8);
            this.tabPage7.Controls.Add(this.comboBox4);
            this.tabPage7.Controls.Add(this.label4);
            this.tabPage7.Controls.Add(this.label5);
            this.tabPage7.Controls.Add(this.comboBox3);
            this.tabPage7.Controls.Add(this.comboBox1);
            this.tabPage7.Controls.Add(this.comboBox2);
            this.tabPage7.Controls.Add(this.label7);
            this.tabPage7.Location = new Point(4, 0x16);
            this.tabPage7.Name = "tabPage7";
            this.tabPage7.Padding = new Padding(3);
            this.tabPage7.Size = new Size(0x17a, 0xc0);
            this.tabPage7.TabIndex = 6;
            this.tabPage7.Text = "Colors";
            this.tabPage7.UseVisualStyleBackColor = true;
            this.button5.Location = new Point(110, 0x9e);
            this.button5.Name = "button5";
            this.button5.Size = new Size(0x65, 0x17);
            this.button5.TabIndex = 0x3e;
            this.button5.Text = "Luigi Trousers";
            this.button5.UseVisualStyleBackColor = true;
            this.button5.Click += new EventHandler(this.button5_Click);
            this.button4.Location = new Point(6, 0x9e);
            this.button4.Name = "button4";
            this.button4.Size = new Size(0x65, 0x17);
            this.button4.TabIndex = 0x3d;
            this.button4.Text = "Luigi Colors";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new EventHandler(this.button4_Click);
            this.button3.Location = new Point(9, 0x7c);
            this.button3.Name = "button3";
            this.button3.Size = new Size(0x65, 0x17);
            this.button3.TabIndex = 60;
            this.button3.Text = "Mario Colors";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new EventHandler(this.button3_Click);
            this.button1.Location = new Point(110, 0x7c);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x65, 0x17);
            this.button1.TabIndex = 0x3b;
            this.button1.Text = "Mario Trousers";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.numericUpDown4.Hexadecimal = true;
            this.numericUpDown4.Location = new Point(0xe7, 0xa6);
            int[] bits = new int[4];
            bits[0] = 0xff;
            this.numericUpDown4.Maximum = new decimal(bits);
            this.numericUpDown4.Name = "numericUpDown4";
            this.numericUpDown4.Size = new Size(0x2b, 20);
            this.numericUpDown4.TabIndex = 0x3a;
            this.numericUpDown4.ValueChanged += new EventHandler(this.numericUpDown4_ValueChanged);
            this.numericUpDown1.Hexadecimal = true;
            this.numericUpDown1.Location = new Point(0xe7, 0x89);
            int[] numArray2 = new int[4];
            numArray2[0] = 0xff;
            this.numericUpDown1.Maximum = new decimal(numArray2);
            this.numericUpDown1.Name = "numericUpDown1";
            this.numericUpDown1.Size = new Size(0x2b, 20);
            this.numericUpDown1.TabIndex = 0x39;
            this.numericUpDown1.ValueChanged += new EventHandler(this.numericUpDown1_ValueChanged_1);
            this.numericUpDown3.Hexadecimal = true;
            this.numericUpDown3.Location = new Point(0xe7, 0x6a);
            int[] numArray3 = new int[4];
            numArray3[0] = 0xff;
            this.numericUpDown3.Maximum = new decimal(numArray3);
            this.numericUpDown3.Name = "numericUpDown3";
            this.numericUpDown3.Size = new Size(0x2b, 20);
            this.numericUpDown3.TabIndex = 0x38;
            this.numericUpDown3.ValueChanged += new EventHandler(this.numericUpDown3_ValueChanged);
            this.label13.AutoSize = true;
            this.label13.Location = new Point(0x3f, 0x62);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x65, 13);
            this.label13.TabIndex = 0x35;
            this.label13.Text = "Apply Custom Color:";
            this.label13.Click += new EventHandler(this.label13_Click);
            this.label12.AutoSize = true;
            this.label12.Location = new Point(290, 0x52);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x45, 13);
            this.label12.TabIndex = 0x31;
            this.label12.Text = "Custom Color";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(0xd5, 0xa8);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x11, 13);
            this.label11.TabIndex = 0x30;
            this.label11.Text = "B:";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(0xd5, 0x6c);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x12, 13);
            this.label10.TabIndex = 0x2f;
            this.label10.Text = "R:";
            this.label10.Click += new EventHandler(this.label10_Click);
            this.label9.AutoSize = true;
            this.label9.Location = new Point(0xd5, 0x8b);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x12, 13);
            this.label9.TabIndex = 10;
            this.label9.Text = "G:";
            this.label9.Click += new EventHandler(this.label9_Click);
            this.panel1.BackColor = Color.Black;
            this.panel1.Location = new Point(280, 0x62);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0x5c, 0x58);
            this.panel1.TabIndex = 4;
            this.panel1.Paint += new PaintEventHandler(this.panel1_Paint);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(0xb8, 0x36);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x4c, 13);
            this.label8.TabIndex = 0x2c;
            this.label8.Text = "Luigi Trousers:";
            this.toolTip1.SetToolTip(this.label8, "This will change the color of Luigi's Trousers.");
            this.label8.Click += new EventHandler(this.label8_Click);
            this.comboBox4.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox4.FormattingEnabled = true;
            object[] items = new object[14];
            items[0] = "Vanilla";
            items[1] = "Green";
            items[2] = "Red";
            items[3] = "Purple";
            items[4] = "Yellow";
            items[5] = "Cyan";
            items[6] = "Blue";
            items[7] = "Pink";
            items[8] = "Orange";
            items[9] = "Black";
            items[10] = "White";
            items[11] = "Random";
            items[12] = "Chaos";
            items[13] = "Custom";
            this.comboBox4.Items.AddRange(items);
            this.comboBox4.Location = new Point(0x10a, 0x33);
            this.comboBox4.Name = "comboBox4";
            this.comboBox4.Size = new Size(0x5d, 0x15);
            this.comboBox4.TabIndex = 0x2b;
            this.comboBox4.SelectedIndexChanged += new EventHandler(this.comboBox4_SelectedIndexChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(6, 0x17);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x44, 13);
            this.label4.TabIndex = 0x21;
            this.label4.Text = "Mario Colors:";
            this.toolTip1.SetToolTip(this.label4, "This will change the color of Mario's hat. This will also change the colors of other things including UI etc.");
            this.label4.Click += new EventHandler(this.label4_Click);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(10, 0x36);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x40, 13);
            this.label5.TabIndex = 0x22;
            this.label5.Text = "Luigi Colors:";
            this.toolTip1.SetToolTip(this.label5, "This will change the color of Luigi's hat. This will also change the colors of other things including UI etc.");
            this.label5.Click += new EventHandler(this.label5_Click);
            this.comboBox3.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox3.FormattingEnabled = true;
            this.comboBox3.ImeMode = ImeMode.NoControl;
            object[] objArray2 = new object[14];
            objArray2[0] = "Vanilla";
            objArray2[1] = "Red";
            objArray2[2] = "Green";
            objArray2[3] = "Purple";
            objArray2[4] = "Yellow";
            objArray2[5] = "Cyan";
            objArray2[6] = "Blue";
            objArray2[7] = "Pink";
            objArray2[8] = "Orange";
            objArray2[9] = "Black";
            objArray2[10] = "White";
            objArray2[11] = "Random";
            objArray2[12] = "Chaos";
            objArray2[13] = "Custom";
            this.comboBox3.Items.AddRange(objArray2);
            this.comboBox3.Location = new Point(0x10a, 20);
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Size = new Size(0x5d, 0x15);
            this.comboBox3.TabIndex = 0x2a;
            this.comboBox3.SelectedIndexChanged += new EventHandler(this.comboBox3_SelectedIndexChanged);
            this.comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.ImeMode = ImeMode.NoControl;
            object[] objArray3 = new object[15];
            objArray3[0] = "Red";
            objArray3[1] = "Green";
            objArray3[2] = "Purple";
            objArray3[3] = "Yellow";
            objArray3[4] = "Cyan";
            objArray3[5] = "Blue";
            objArray3[6] = "Pink";
            objArray3[7] = "Orange";
            objArray3[8] = "Black";
            objArray3[9] = "White";
            objArray3[10] = "Random";
            objArray3[11] = "Chaos";
            objArray3[12] = "TrueChaos";
            objArray3[13] = "Silhouette";
            objArray3[14] = "Custom";
            this.comboBox1.Items.AddRange(objArray3);
            this.comboBox1.Location = new Point(80, 20);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(0x5d, 0x15);
            this.comboBox1.TabIndex = 10;
            this.comboBox1.SelectedIndexChanged += new EventHandler(this.comboBox1_SelectedIndexChanged);
            this.comboBox2.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox2.FormattingEnabled = true;
            object[] objArray4 = new object[15];
            objArray4[0] = "Green";
            objArray4[1] = "Red";
            objArray4[2] = "Purple";
            objArray4[3] = "Yellow";
            objArray4[4] = "Cyan";
            objArray4[5] = "Blue";
            objArray4[6] = "Pink";
            objArray4[7] = "Orange";
            objArray4[8] = "Black";
            objArray4[9] = "White";
            objArray4[10] = "Random";
            objArray4[11] = "Chaos";
            objArray4[12] = "TrueChaos";
            objArray4[13] = "Silhouette";
            objArray4[14] = "Custom";
            this.comboBox2.Items.AddRange(objArray4);
            this.comboBox2.Location = new Point(80, 0x33);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new Size(0x5d, 0x15);
            this.comboBox2.TabIndex = 0x20;
            this.comboBox2.SelectedIndexChanged += new EventHandler(this.comboBox2_SelectedIndexChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(0xb8, 0x17);
            this.label7.Name = "label7";
            this.label7.Size = new Size(80, 13);
            this.label7.TabIndex = 0x29;
            this.label7.Text = "Mario Trousers:";
            this.toolTip1.SetToolTip(this.label7, "This will change the color of Mario's Trousers.");
            this.tabPage9.Controls.Add(this.checkBox48);
            this.tabPage9.Controls.Add(this.checkBox40);
            this.tabPage9.Controls.Add(this.label14);
            this.tabPage9.Controls.Add(this.radioButton6);
            this.tabPage9.Controls.Add(this.radioButton7);
            this.tabPage9.Controls.Add(this.radioButton8);
            this.tabPage9.Controls.Add(this.checkBox25);
            this.tabPage9.Controls.Add(this.checkBox31);
            this.tabPage9.Location = new Point(4, 0x16);
            this.tabPage9.Name = "tabPage9";
            this.tabPage9.Padding = new Padding(3);
            this.tabPage9.Size = new Size(0x17a, 0xc0);
            this.tabPage9.TabIndex = 7;
            this.tabPage9.Text = "Enemies";
            this.tabPage9.UseVisualStyleBackColor = true;
            this.checkBox48.AutoSize = true;
            this.checkBox48.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox48.Location = new Point(0x34, 0x8b);
            this.checkBox48.Name = "checkBox48";
            this.checkBox48.Size = new Size(0x70, 0x11);
            this.checkBox48.TabIndex = 0x2c;
            this.checkBox48.Text = "Tattle Enemy HP?";
            this.toolTip1.SetToolTip(this.checkBox48, "This will show you the current and max HP of all enemies and bosses.\r\nYou can see it while you are hovering over the enemy to attack in the top left corner of the screen.");
            this.checkBox48.UseVisualStyleBackColor = true;
            this.checkBox48.CheckedChanged += new EventHandler(this.checkBox48_CheckedChanged);
            this.checkBox40.AutoSize = true;
            this.checkBox40.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox40.Location = new Point(0x2a, 0x68);
            this.checkBox40.Name = "checkBox40";
            this.checkBox40.Size = new Size(0x7a, 0x11);
            this.checkBox40.TabIndex = 0x2b;
            this.checkBox40.Text = "Scale enemy POW?";
            this.toolTip1.SetToolTip(this.checkBox40, "This will scale the POW of all Enemies and Bosses to the area you are in.");
            this.checkBox40.UseVisualStyleBackColor = true;
            this.checkBox40.CheckedChanged += new EventHandler(this.checkBox40_CheckedChanged);
            this.label14.AutoSize = true;
            this.label14.Location = new Point(0xcf, 0x13);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x67, 13);
            this.label14.TabIndex = 0x2a;
            this.label14.Text = "Randomize Bosses?";
            this.radioButton6.AutoSize = true;
            this.radioButton6.Location = new Point(0xd1, 0x51);
            this.radioButton6.Name = "radioButton6";
            this.radioButton6.Size = new Size(0x41, 0x11);
            this.radioButton6.TabIndex = 0x29;
            this.radioButton6.Text = "Random";
            this.toolTip1.SetToolTip(this.radioButton6, "Bosses can appear anywhere in the game including in normal fights.");
            this.radioButton6.UseVisualStyleBackColor = true;
            this.radioButton6.CheckedChanged += new EventHandler(this.radioButton6_CheckedChanged);
            this.radioButton7.AutoSize = true;
            this.radioButton7.Location = new Point(0xd1, 0x3a);
            this.radioButton7.Name = "radioButton7";
            this.radioButton7.Size = new Size(0x62, 0x11);
            this.radioButton7.TabIndex = 40;
            this.radioButton7.Text = "Boss < - > Boss";
            this.toolTip1.SetToolTip(this.radioButton7, "Bosses will only be randomized with other bosses.");
            this.radioButton7.UseVisualStyleBackColor = true;
            this.radioButton7.CheckedChanged += new EventHandler(this.radioButton7_CheckedChanged);
            this.radioButton8.AutoSize = true;
            this.radioButton8.Checked = true;
            this.radioButton8.Location = new Point(0xd1, 0x23);
            this.radioButton8.Name = "radioButton8";
            this.radioButton8.Size = new Size(0x55, 0x11);
            this.radioButton8.TabIndex = 0x27;
            this.radioButton8.TabStop = true;
            this.radioButton8.Text = "Not Random";
            this.toolTip1.SetToolTip(this.radioButton8, "Bosses will not be randomized.");
            this.radioButton8.UseVisualStyleBackColor = true;
            this.radioButton8.CheckedChanged += new EventHandler(this.radioButton8_CheckedChanged);
            this.checkBox25.AutoSize = true;
            this.checkBox25.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox25.Location = new Point(0x24, 0x2a);
            this.checkBox25.Name = "checkBox25";
            this.checkBox25.Size = new Size(0x80, 0x11);
            this.checkBox25.TabIndex = 0x1d;
            this.checkBox25.Text = "Randomize Enemies?";
            this.toolTip1.SetToolTip(this.checkBox25, "Checking this will randomize all Enemies in the game.\r\nIt is recommended to use the stat scaling options as well, the game is very difficult without them.");
            this.checkBox25.UseVisualStyleBackColor = true;
            this.checkBox25.CheckedChanged += new EventHandler(this.checkBox25_CheckedChanged);
            this.checkBox31.AutoSize = true;
            this.checkBox31.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox31.Location = new Point(15, 0x51);
            this.checkBox31.Name = "checkBox31";
            this.checkBox31.Size = new Size(0x95, 0x11);
            this.checkBox31.TabIndex = 0x26;
            this.checkBox31.Text = "Scale enemy HP and XP?";
            this.toolTip1.SetToolTip(this.checkBox31, "This will scale the HP and XP of all enemies and bosses to the area you are in.");
            this.checkBox31.UseVisualStyleBackColor = true;
            this.checkBox31.CheckedChanged += new EventHandler(this.checkBox31_CheckedChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(0x9e, 0x121);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x3e, 13);
            this.label6.TabIndex = 0x25;
            this.label6.Text = "Seed Type:";
            this.label6.Click += new EventHandler(this.label6_Click);
            this.radioButton5.AutoSize = true;
            this.radioButton5.Location = new Point(0x117, 0x120);
            this.radioButton5.Name = "radioButton5";
            this.radioButton5.Size = new Size(0x33, 0x11);
            this.radioButton5.TabIndex = 0x24;
            this.radioButton5.TabStop = true;
            this.radioButton5.Text = "100%";
            this.toolTip1.SetToolTip(this.radioButton5, "This will make sure that the game is beatable and that every item in the game is obtainable.");
            this.radioButton5.UseVisualStyleBackColor = true;
            this.radioButton5.CheckedChanged += new EventHandler(this.radioButton5_CheckedChanged);
            this.radioButton4.AutoSize = true;
            this.radioButton4.Checked = true;
            this.radioButton4.Location = new Point(0xe2, 0x120);
            this.radioButton4.Name = "radioButton4";
            this.radioButton4.Size = new Size(0x33, 0x11);
            this.radioButton4.TabIndex = 0x23;
            this.radioButton4.TabStop = true;
            this.radioButton4.Text = "Any%";
            this.toolTip1.SetToolTip(this.radioButton4, "The game will check only that the game can be beaten. Some items may be unobtainable.");
            this.radioButton4.UseVisualStyleBackColor = true;
            this.radioButton4.CheckedChanged += new EventHandler(this.radioButton4_CheckedChanged);
            this.statCountBindingSource.DataSource = typeof(Rom.StatCount);
            this.tabControl2.Controls.Add(this.tabPage8);
            this.tabControl2.Location = new Point(0x19, 0x22);
            this.tabControl2.Name = "tabControl2";
            this.tabControl2.SelectedIndex = 0;
            this.tabControl2.Size = new Size(0x182, 0xd8);
            this.tabControl2.TabIndex = 4;
            this.tabControl2.Visible = false;
            this.tabPage8.Controls.Add(this.checkBox35);
            this.tabPage8.Location = new Point(4, 0x16);
            this.tabPage8.Name = "tabPage8";
            this.tabPage8.Padding = new Padding(3);
            this.tabPage8.Size = new Size(0x17a, 190);
            this.tabPage8.TabIndex = 1;
            this.tabPage8.Text = "Items";
            this.tabPage8.UseVisualStyleBackColor = true;
            this.checkBox35.AutoSize = true;
            this.checkBox35.CheckAlign = ContentAlignment.MiddleRight;
            this.checkBox35.Checked = true;
            this.checkBox35.CheckState = CheckState.Checked;
            this.checkBox35.Location = new Point(9, 0x11);
            this.checkBox35.Name = "checkBox35";
            this.checkBox35.Size = new Size(0x4c, 0x11);
            this.checkBox35.TabIndex = 0;
            this.checkBox35.Text = "Everything";
            this.checkBox35.UseVisualStyleBackColor = true;
            this.checkBox35.CheckedChanged += new EventHandler(this.checkBox35_CheckedChanged);
            this.saveFileDialog2.DefaultExt = "nds";
            this.saveFileDialog2.Filter = "Nintendo DS Rom (*.nds)|*.nds|All files (*.*)|*.*";
            this.saveFileDialog2.FileOk += new CancelEventHandler(this.saveFileDialog2_FileOk);
            this.button6.Location = new Point(0x6d, 0x103);
            this.button6.Name = "button6";
            this.button6.Size = new Size(0x61, 0x17);
            this.button6.TabIndex = 10;
            this.button6.Text = "Save Settings...";
            this.toolTip1.SetToolTip(this.button6, "Save a settings config.");
            this.button6.UseVisualStyleBackColor = true;
            this.button6.Click += new EventHandler(this.button6_Click);
            this.button7.Location = new Point(12, 0x103);
            this.button7.Name = "button7";
            this.button7.Size = new Size(0x5b, 0x17);
            this.button7.TabIndex = 11;
            this.button7.Text = "Load Settings...";
            this.toolTip1.SetToolTip(this.button7, "Load a settings config.");
            this.button7.UseVisualStyleBackColor = true;
            this.button7.Click += new EventHandler(this.button7_Click);
            this.openFileDialog2.FileName = "openFileDialog2";
            this.openFileDialog2.FileOk += new CancelEventHandler(this.openFileDialog2_FileOk);
            this.saveFileDialog3.DefaultExt = "txt";
            this.saveFileDialog3.Filter = "Text File (*.txt)|*.txt|All files (*.*)|*.*";
            this.saveFileDialog3.FileOk += new CancelEventHandler(this.saveFileDialog2_FileOk);
            this.checkBox49.AutoSize = true;
            this.checkBox49.Location = new Point(12, 0x120);
            this.checkBox49.Name = "checkBox49";
            this.checkBox49.Size = new Size(140, 0x11);
            this.checkBox49.TabIndex = 12;
            this.checkBox49.Text = "Randomize All Settings?";
            this.toolTip1.SetToolTip(this.checkBox49, "Checking this will randomize all settings when you click Rnandomize.");
            this.checkBox49.UseVisualStyleBackColor = true;
            this.checkBox49.CheckedChanged += new EventHandler(this.checkBox49_CheckedChanged);
            this.form1BindingSource.DataSource = typeof(Form1);
            this.form1BindingSource1.DataSource = typeof(Form1);
            this.romBindingSource.DataSource = typeof(Rom);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(430, 0x13a);
            base.Controls.Add(this.checkBox49);
            base.Controls.Add(this.button7);
            base.Controls.Add(this.button6);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.SeedTextbox);
            base.Controls.Add(this.button2);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.textBox1);
            base.Controls.Add(this.radioButton5);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.radioButton4);
            base.Controls.Add(this.SelectRomButton);
            base.Controls.Add(this.Colors);
            base.Controls.Add(this.tabControl2);
            base.Name = "Form1";
            this.Text = "MLSS Randomizer";
            base.Load += new EventHandler(this.Form1_Load);
            this.Colors.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.tabPage4.ResumeLayout(false);
            this.tabPage4.PerformLayout();
            this.tabPage6.ResumeLayout(false);
            this.tabPage6.PerformLayout();
            this.tabPage5.ResumeLayout(false);
            this.tabPage5.PerformLayout();
            this.tabPage7.ResumeLayout(false);
            this.tabPage7.PerformLayout();
            this.numericUpDown4.EndInit();
            this.numericUpDown1.EndInit();
            this.numericUpDown3.EndInit();
            this.tabPage9.ResumeLayout(false);
            this.tabPage9.PerformLayout();
            ((ISupportInitialize)this.statCountBindingSource).EndInit();
            this.tabControl2.ResumeLayout(false);
            this.tabPage8.ResumeLayout(false);
            this.tabPage8.PerformLayout();
            ((ISupportInitialize)this.form1BindingSource).EndInit();
            ((ISupportInitialize)this.form1BindingSource1).EndInit();
            ((ISupportInitialize)this.romBindingSource).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion
        private Button SelectRomButton;
        private TextBox textBox1;
        private Label label1;
        private Button button2;
        private DirectorySearcher directorySearcher1;
        private FolderBrowserDialog folderBrowserDialog1;
        private OpenFileDialog openFileDialog1;
        private TextBox SeedTextbox;
        private Label label2;
        private SaveFileDialog saveFileDialog1;
        private CheckBox checkBox1;
        private TabControl Colors;
        private TabPage tabPage1;
        private TabPage tabPage2;
        private CheckBox checkBox18;
        private CheckBox checkBox10;
        private CheckBox checkBox9;
        private CheckBox checkBox8;
        private CheckBox checkBox7;
        private CheckBox checkBox6;
        private CheckBox checkBox5;
        private CheckBox checkBox4;
        private CheckBox checkBox3;
        private CheckBox checkBox2;
        private CheckBox checkBox17;
        private CheckBox checkBox16;
        private CheckBox checkBox15;
        private CheckBox checkBox14;
        private CheckBox checkBox13;
        private CheckBox checkBox12;
        private CheckBox checkBox11;
        private CheckBox checkBox19;
        private CheckBox checkBox21;
        private CheckBox checkBox20;
        private TabPage tabPage3;
        private CheckBox checkBox22;
        private RadioButton radioButton1;
        private Label label3;
        private RadioButton radioButton3;
        private RadioButton radioButton2;
        private TabPage tabPage4;
        private TabPage tabPage5;
        private CheckBox checkBox23;
        private CheckBox checkBox24;
        private CheckBox checkBox25;
        private TabPage tabPage6;
        private CheckBox checkBox26;
        private CheckBox checkBox28;
        private CheckBox checkBox27;
        private CheckBox checkBox29;
        private CheckBox checkBox30;
        private ComboBox comboBox2;
        private ComboBox comboBox1;
        private BindingSource form1BindingSource;
        private BindingSource form1BindingSource1;
        private BindingSource romBindingSource;
        private BindingSource statCountBindingSource;
        private Label label5;
        private Label label4;
        private RadioButton radioButton5;
        private RadioButton radioButton4;
        private Label label6;
        private CheckBox checkBox31;
        private CheckBox checkBox32;
        private CheckBox checkBox34;
        private ComboBox comboBox3;
        private Label label7;
        private Label label8;
        private ComboBox comboBox4;
        private TabControl tabControl2;
        private TabPage tabPage8;
        private CheckBox checkBox35;
        private SaveFileDialog saveFileDialog2;
        private Panel panel1;
        private TabPage tabPage7;
        private Label label9;
        private Label label11;
        private Label label10;
        private Label label12;
        private Label label13;
        private NumericUpDown numericUpDown4;
        private NumericUpDown numericUpDown1;
        private NumericUpDown numericUpDown3;
        private Button button5;
        private Button button4;
        private Button button3;
        private Button button1;
        private CheckBox checkBox36;
        private Button button6;
        private Button button7;
        private OpenFileDialog openFileDialog2;
        private SaveFileDialog saveFileDialog3;
        private TabPage tabPage9;
        private Label label14;
        private RadioButton radioButton6;
        private RadioButton radioButton7;
        private RadioButton radioButton8;
        private CheckBox checkBox33;
        private CheckBox checkBox37;
        private CheckBox checkBox38;
        private CheckBox checkBox39;
        private CheckBox checkBox40;
        private CheckBox checkBox42;
        private CheckBox checkBox41;
        private CheckBox checkBox43;
        private CheckBox checkBox45;
        private CheckBox checkBox44;
        private CheckBox checkBox46;
        private ToolTip toolTip1;
        private CheckBox checkBox47;
        private CheckBox checkBox48;
        private CheckBox checkBox49;
        private CheckBox checkBox50;
        private CheckBox checkBox51;
        private CheckBox checkBox52;
    }
}

